version: '3'
services:
  react-native:
    build: .
    volumes:
      - .:/workspace:cached
      - ~/.ssh:/home/vscode/.ssh:ro
    ports:
      - "8081:8081"
    command: /bin/sh -c "while sleep 1000; do :; done"
