version: '3.8'
services:
  react-native:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/workspace:cached
      - ~/.ssh:/home/node/.ssh:ro
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "19000:19000"
      - "19001:19001"
      - "8081:8081"
    environment:
      - ANDROID_SDK_ROOT=/usr/local/android-sdk
      - PATH=${PATH}:/usr/local/android-sdk/cmdline-tools/latest/bin:/usr/local/android-sdk/platform-tools
    command: /bin/sh -c "while sleep 1000; do :; done"
    devices:
      - "/dev/kvm"
    privileged: true
